import { User, Post, Notification, Message, Trend, UserList, Reply, Draft, Space, Community, AnalyticsData } from './types';

export const currentUser: User = {
  id: '1',
  name: 'Amani Tech',
  handle: '@amanitech',
  avatar: '👨‍💻',
  bio: '🚀 Full Stack Developer | Building the future | Open Source Contributor | Tech Enthusiast from Tanzania 🇹🇿',
  verified: true,
  premium: true,
  followers: 15420,
  following: 892,
  posts: 3241,
  joinedDate: 'March 2019',
  location: 'Dar es Salaam, Tanzania',
  website: 'amanitech.dev',
  isFollowing: false,
};

export const users: User[] = [
  currentUser,
  {
    id: '2',
    name: 'Zawadi Innovation',
    handle: '@zawadi_innov',
    avatar: '👩‍🔬',
    bio: 'Innovation Lead @TechAfrica | AI & ML Researcher | Speaker',
    verified: true,
    premium: true,
    followers: 89200,
    following: 432,
    posts: 12500,
    joinedDate: 'January 2018',
    location: 'Nairobi, Kenya',
    isFollowing: true,
  },
  {
    id: '3',
    name: 'Baraka Digital',
    handle: '@barakadigital',
    avatar: '🎨',
    bio: 'UI/UX Designer | Creative Director | Making pixels beautiful ✨',
    verified: true,
    premium: false,
    followers: 45600,
    following: 1200,
    posts: 8900,
    joinedDate: 'June 2020',
    isFollowing: false,
  },
  {
    id: '4',
    name: 'Neema AI',
    handle: '@neema_ai',
    avatar: '🤖',
    bio: 'Artificial Intelligence Researcher | Deep Learning | NLP | Building the future of AI',
    verified: true,
    premium: true,
    followers: 125000,
    following: 234,
    posts: 5600,
    joinedDate: 'September 2017',
    location: 'San Francisco, CA',
    isFollowing: true,
  },
  {
    id: '5',
    name: 'Furaha Dev',
    handle: '@furahadev',
    avatar: '👨‍🎓',
    bio: 'Software Engineer @BigTech | React | TypeScript | Node.js',
    verified: false,
    premium: false,
    followers: 8900,
    following: 567,
    posts: 2340,
    joinedDate: 'February 2021',
    isFollowing: false,
  },
  {
    id: '6',
    name: 'Upendo Crypto',
    handle: '@upendo_crypto',
    avatar: '💎',
    bio: 'Blockchain Developer | Web3 Enthusiast | DeFi Builder | Ethereum Maximalist',
    verified: true,
    premium: true,
    followers: 67800,
    following: 345,
    posts: 9800,
    joinedDate: 'April 2019',
    isFollowing: true,
  },
  {
    id: '7',
    name: 'Rehema Cloud',
    handle: '@rehemacloud',
    avatar: '☁️',
    bio: 'Cloud Architect | AWS | GCP | DevOps | Infrastructure as Code',
    verified: true,
    premium: false,
    followers: 34500,
    following: 678,
    posts: 6700,
    joinedDate: 'July 2018',
    isFollowing: false,
  },
  {
    id: '8',
    name: 'Jabali Security',
    handle: '@jabali_sec',
    avatar: '🛡️',
    bio: 'Cybersecurity Expert | Penetration Testing | Bug Bounty Hunter | CTF Player',
    verified: true,
    premium: true,
    followers: 52300,
    following: 189,
    posts: 4200,
    joinedDate: 'November 2019',
    isFollowing: false,
  },
];

export const replies: Record<string, Reply[]> = {
  '1': [
    { id: 'r1', user: users[4], content: 'This is incredible! Can\'t wait to try it out 🚀', timestamp: new Date(Date.now() - 1000 * 60 * 3), likes: 23, liked: false, replies: 2 },
    { id: 'r2', user: users[6], content: 'Does it support multi-language codebases?', timestamp: new Date(Date.now() - 1000 * 60 * 2), likes: 8, liked: false, replies: 0 },
    { id: 'r3', user: users[2], content: 'The UI looks amazing! Great work team 👏', timestamp: new Date(Date.now() - 1000 * 60 * 1), likes: 45, liked: false, replies: 1 },
  ],
  '3': [
    { id: 'r4', user: users[0], content: 'This is groundbreaking! When can we access the API?', timestamp: new Date(Date.now() - 1000 * 60 * 25), likes: 156, liked: false, replies: 12 },
    { id: 'r5', user: users[5], content: 'The implications for blockchain are enormous too', timestamp: new Date(Date.now() - 1000 * 60 * 20), likes: 89, liked: false, replies: 5 },
    { id: 'r6', user: users[7], content: 'What about safety measures? This needs careful deployment.', timestamp: new Date(Date.now() - 1000 * 60 * 15), likes: 234, liked: false, replies: 18 },
    { id: 'r7', user: users[4], content: 'I\'ve been testing the beta and it\'s phenomenal!', timestamp: new Date(Date.now() - 1000 * 60 * 10), likes: 67, liked: false, replies: 3 },
  ],
  '7': [
    { id: 'r8', user: users[1], content: 'Congratulations! Well deserved 🎉', timestamp: new Date(Date.now() - 1000 * 60 * 150), likes: 345, liked: false, replies: 4 },
    { id: 'r9', user: users[3], content: 'Open source for the win! 🙌', timestamp: new Date(Date.now() - 1000 * 60 * 140), likes: 178, liked: false, replies: 2 },
  ],
};

export const posts: Post[] = [
  {
    id: '1',
    user: users[1],
    content: '🚀 Just launched our new AI-powered code review tool! It can detect bugs, suggest improvements, and even write documentation automatically.\n\nThe future of software development is here. What features would you like to see next?\n\n#AI #DevTools #Innovation',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    likes: 2341,
    retweets: 567,
    replies: 189,
    views: 89000,
    bookmarks: 432,
    liked: false,
    retweeted: false,
    bookmarked: false,
    isPremium: true,
    replyList: replies['1'],
  },
  {
    id: '2',
    user: users[2],
    content: '🎨 Design tip of the day:\n\nWhite space is not empty space — it\'s a powerful design element. Use it wisely to create hierarchy, improve readability, and make your designs breathe.\n\nLess is truly more in modern UI design.',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    likes: 1892,
    retweets: 445,
    replies: 78,
    views: 56000,
    bookmarks: 890,
    liked: true,
    retweeted: false,
    bookmarked: false,
  },
  {
    id: '3',
    user: users[3],
    content: '🤖 Breaking: Our latest language model just passed the Turing test with 94% accuracy across 1000 evaluators.\n\nWe\'re entering a new era of human-AI interaction. The implications for education, healthcare, and creative industries are enormous.\n\nFull paper dropping next week.',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    likes: 15600,
    retweets: 4500,
    replies: 2300,
    views: 1200000,
    bookmarks: 8900,
    liked: false,
    retweeted: true,
    bookmarked: true,
    isPremium: true,
    replyList: replies['3'],
  },
  {
    id: '4',
    user: users[4],
    content: '💡 Hot take: TypeScript is not just "JavaScript with types." It\'s a completely different way of thinking about software architecture.\n\nOnce you go TS, you never go back. The confidence it gives you when refactoring is unmatched.',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    likes: 3456,
    retweets: 789,
    replies: 567,
    views: 145000,
    bookmarks: 234,
    liked: false,
    retweeted: false,
    bookmarked: false,
    poll: {
      id: 'poll1',
      question: 'What\'s your primary programming language?',
      options: [
        { id: 'opt1', text: 'TypeScript/JavaScript', votes: 4521, percentage: 45, voted: false },
        { id: 'opt2', text: 'Python', votes: 2890, percentage: 29, voted: false },
        { id: 'opt3', text: 'Go', votes: 1456, percentage: 15, voted: false },
        { id: 'opt4', text: 'Rust', votes: 1133, percentage: 11, voted: false },
      ],
      totalVotes: 10000,
      endsAt: new Date(Date.now() + 1000 * 60 * 60 * 18),
      hasVoted: false,
    },
  },
  {
    id: '5',
    user: users[5],
    content: '🔗 Web3 is not dead. It\'s just evolving.\n\nThe next wave of blockchain applications will focus on:\n\n• Real-world asset tokenization\n• Decentralized identity\n• Cross-chain interoperability\n• Zero-knowledge proofs for privacy\n\nWe\'re building the infrastructure for the next internet.',
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
    likes: 5678,
    retweets: 1234,
    replies: 456,
    views: 234000,
    bookmarks: 1567,
    liked: false,
    retweeted: false,
    bookmarked: false,
    isPremium: true,
  },
  {
    id: '6',
    user: users[6],
    content: '☁️ Cloud cost optimization checklist:\n\n✅ Right-size your instances\n✅ Use spot/preemptible instances\n✅ Implement auto-scaling\n✅ Clean up unused resources\n✅ Use reserved instances for predictable workloads\n✅ Monitor with cost alerts\n\nSaved our company $200K/year with these simple steps.',
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    likes: 8901,
    retweets: 2345,
    replies: 345,
    views: 567000,
    bookmarks: 4567,
    liked: true,
    retweeted: false,
    bookmarked: false,
  },
  {
    id: '7',
    user: users[0],
    content: '🌍 Excited to announce that our open-source project just hit 10,000 stars on GitHub!\n\nThank you to every contributor, bug reporter, and community member who made this possible.\n\nOpen source is the future. Let\'s keep building together! 🙏\n\n#OpenSource #GitHub #Community',
    timestamp: new Date(Date.now() - 1000 * 60 * 180),
    likes: 12345,
    retweets: 3456,
    replies: 789,
    views: 890000,
    bookmarks: 2345,
    liked: false,
    retweeted: false,
    bookmarked: false,
    pinned: true,
    isPremium: true,
    isOwn: true,
    replyList: replies['7'],
  },
];

export const notifications: Notification[] = [
  {
    id: '1',
    type: 'like',
    user: users[1],
    content: 'liked your post',
    postContent: '🌍 Excited to announce that our open-source project...',
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
    read: false,
  },
  {
    id: '2',
    type: 'retweet',
    user: users[3],
    content: 'reposted your post',
    postContent: '🌍 Excited to announce that our open-source project...',
    timestamp: new Date(Date.now() - 1000 * 60 * 10),
    read: false,
  },
  {
    id: '3',
    type: 'follow',
    user: users[4],
    content: 'followed you',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    read: false,
  },
  {
    id: '4',
    type: 'mention',
    user: users[2],
    content: 'mentioned you in a post',
    postContent: 'Great insights from @amanitech on open source development!',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    read: true,
  },
  {
    id: '5',
    type: 'reply',
    user: users[5],
    content: 'replied to your post',
    postContent: 'What do you think about the future of Web3?',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    read: true,
  },
  {
    id: '6',
    type: 'like',
    user: users[6],
    content: 'liked your reply',
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
    read: true,
  },
  {
    id: '7',
    type: 'follow',
    user: users[7],
    content: 'followed you',
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    read: true,
  },
];

export const messages: Message[] = [
  {
    id: '1',
    user: users[1],
    lastMessage: 'Hey! Did you see the new AI features?',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    unread: true,
    messages: [
      { id: 'm1', text: 'Hey Amani! 👋', sent: false, time: '10:15 AM' },
      { id: 'm2', text: 'Hi Zawadi! How are you?', sent: true, time: '10:18 AM' },
      { id: 'm3', text: 'I\'m great! We just shipped something exciting', sent: false, time: '10:20 AM' },
      { id: 'm4', text: 'Oh really? Tell me more!', sent: true, time: '10:22 AM' },
      { id: 'm5', text: 'Hey! Did you see the new AI features?', sent: false, time: '10:30 AM' },
    ],
  },
  {
    id: '2',
    user: users[2],
    lastMessage: 'The design mockups are ready for review 🎨',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    unread: true,
    messages: [
      { id: 'm6', text: 'Hey, I\'ve been working on the new UI', sent: false, time: '9:00 AM' },
      { id: 'm7', text: 'Awesome! Can\'t wait to see it', sent: true, time: '9:05 AM' },
      { id: 'm8', text: 'The design mockups are ready for review 🎨', sent: false, time: '9:30 AM' },
    ],
  },
  {
    id: '3',
    user: users[3],
    lastMessage: 'Let\'s schedule a call about the research paper',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    unread: false,
    messages: [
      { id: 'm9', text: 'The paper is almost done', sent: false, time: '8:00 AM' },
      { id: 'm10', text: 'Great progress! When can we review?', sent: true, time: '8:15 AM' },
      { id: 'm11', text: 'Let\'s schedule a call about the research paper', sent: false, time: '8:30 AM' },
    ],
  },
  {
    id: '4',
    user: users[5],
    lastMessage: 'Check out this smart contract pattern I found',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
    unread: false,
    messages: [
      { id: 'm12', text: 'Found something interesting in DeFi', sent: false, time: '5:00 AM' },
      { id: 'm13', text: 'Check out this smart contract pattern I found', sent: false, time: '5:30 AM' },
    ],
  },
];

export const trends: Trend[] = [
  { id: '1', category: 'Technology · Trending', name: '#AIRevolution', posts: '125K posts', description: 'Artificial Intelligence is transforming every industry' },
  { id: '2', category: 'Trending in Tanzania', name: '#TechAfrica', posts: '89.2K posts', description: 'African tech ecosystem growing rapidly' },
  { id: '3', category: 'Programming · Trending', name: 'TypeScript 6.0', posts: '67.8K posts', description: 'New features in the latest TypeScript release' },
  { id: '4', category: 'Business · Trending', name: '#StartupLife', posts: '45.6K posts', description: 'Entrepreneurs sharing their journey' },
  { id: '5', category: 'Science · Trending', name: 'Quantum Computing', posts: '34.5K posts', description: 'Breakthroughs in quantum technology' },
  { id: '6', category: 'Trending in East Africa', name: '#Innovation2026', posts: '28.9K posts', description: 'New innovations shaping the future' },
  { id: '7', category: 'Technology · Trending', name: '#WebDevelopment', posts: '23.4K posts', description: 'Latest trends in web development' },
  { id: '8', category: 'Entertainment · Trending', name: '#OpenSource', posts: '19.8K posts', description: 'Open source projects making impact' },
  { id: '9', category: 'Sports · Trending', name: '#eSports2026', posts: '15.6K posts', description: 'Competitive gaming reaches new heights' },
  { id: '10', category: 'Music · Trending', name: '#Afrobeats', posts: '12.3K posts', description: 'African music taking over the world' },
];

export const userLists: UserList[] = [
  { id: '1', name: 'Tech Leaders', members: 45, description: 'Top tech influencers and innovators', isPrivate: false, followers: 1200, memberUsers: [users[1], users[3], users[4]] },
  { id: '2', name: 'AI Researchers', members: 23, description: 'Artificial intelligence experts', isPrivate: false, followers: 890, memberUsers: [users[3], users[7]] },
  { id: '3', name: 'Design Inspiration', members: 67, description: 'Creative designers and artists', isPrivate: true, followers: 2300, memberUsers: [users[2]] },
  { id: '4', name: 'Startup Founders', members: 34, description: 'Entrepreneurs building the future', isPrivate: false, followers: 560, memberUsers: [users[5], users[6]] },
];

export const suggestedLists: UserList[] = [
  { id: 's1', name: 'Top Tech Voices', members: 250, description: 'The most influential voices in tech', isPrivate: false, followers: 12500 },
  { id: 's2', name: 'AI & Machine Learning', members: 180, description: 'Everything about AI and ML', isPrivate: false, followers: 8200 },
  { id: 's3', name: 'Startup Ecosystem', members: 120, description: 'Startups, VCs, and innovation', isPrivate: false, followers: 5700 },
  { id: 's4', name: 'Web3 Builders', members: 95, description: 'Blockchain and DeFi developers', isPrivate: false, followers: 4300 },
];

export const emojiList = ['😀', '😂', '🥰', '😎', '🤔', '👍', '👏', '🙌', '🔥', '💯', '🚀', '💡', '🎉', '❤️', '💪', '✨', '🌟', '🎯', '💻', '🤖', '☁️', '🔗', '🛡️', '📱', '⚡', '🌍', '🇹🇿', '🇰🇪', '🏆', '📊'];

export const initialDrafts: Draft[] = [
  {
    id: 'd1',
    content: 'Thinking about writing a thread on AI safety...',
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'd2',
    content: 'Great insights from today\'s tech conference! Key takeaways:\n\n1. AI is transforming everything\n2. Open source is winning\n3. Community matters most',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
];

export const spaces: Space[] = [
  {
    id: 'sp1',
    title: 'The Future of AI in Africa',
    host: users[3],
    speakers: [users[1], users[3], users[7]],
    listeners: 2340,
    isLive: true,
    startedAt: new Date(Date.now() - 1000 * 60 * 45),
    description: 'Discussing how AI will shape the African tech ecosystem in the next decade',
    tags: ['AI', 'Africa', 'Tech', 'Future'],
  },
  {
    id: 'sp2',
    title: 'Web3 Builders Roundtable',
    host: users[5],
    speakers: [users[5], users[6]],
    listeners: 890,
    isLive: true,
    startedAt: new Date(Date.now() - 1000 * 60 * 20),
    description: 'Weekly discussion on blockchain development and DeFi',
    tags: ['Web3', 'Blockchain', 'DeFi'],
  },
  {
    id: 'sp3',
    title: 'Design Systems at Scale',
    host: users[2],
    speakers: [users[2]],
    listeners: 567,
    isLive: false,
    startedAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
    description: 'How to build and maintain design systems for large organizations',
    tags: ['Design', 'UI/UX', 'Systems'],
  },
];

export const communities: Community[] = [
  {
    id: 'c1',
    name: 'React Developers',
    description: 'A community for React developers to share knowledge, ask questions, and discuss best practices.',
    avatar: '⚛️',
    members: 45600,
    isMember: true,
    isPrivate: false,
    admin: users[4],
    rules: ['Be respectful', 'No spam', 'Stay on topic', 'Help others'],
    topics: ['React', 'JavaScript', 'Frontend', 'Web Development'],
  },
  {
    id: 'c2',
    name: 'AI & Machine Learning',
    description: 'Explore the latest in artificial intelligence and machine learning research and applications.',
    avatar: '🤖',
    members: 89200,
    isMember: true,
    isPrivate: false,
    admin: users[3],
    rules: ['Scientific discussions only', 'Cite sources', 'No misinformation'],
    topics: ['AI', 'ML', 'Deep Learning', 'NLP', 'Computer Vision'],
  },
  {
    id: 'c3',
    name: 'African Tech Hub',
    description: 'Connecting tech innovators across Africa. Share opportunities, collaborate on projects.',
    avatar: '🌍',
    members: 23400,
    isMember: false,
    isPrivate: false,
    admin: users[1],
    rules: ['Africa-focused content', 'Support local talent', 'Share opportunities'],
    topics: ['Africa', 'Tech', 'Startups', 'Innovation'],
  },
  {
    id: 'c4',
    name: 'Open Source Contributors',
    description: 'For developers who contribute to open source projects. Share your work and find collaborators.',
    avatar: '💻',
    members: 67800,
    isMember: false,
    isPrivate: false,
    admin: users[0],
    rules: ['Share your contributions', 'Help newcomers', 'No self-promotion spam'],
    topics: ['Open Source', 'GitHub', 'Contributing', 'FOSS'],
  },
];

export const analyticsData: AnalyticsData = {
  period: '30d',
  impressions: 1250000,
  engagements: 89000,
  engagementRate: 7.12,
  followers: 15420,
  followersChange: 1240,
  topPosts: posts.slice(0, 3),
  profileVisits: 34500,
  mentions: 2340,
};
