import { User, Post, Notification, Message, Trend } from './types';

export const currentUser: User = {
  id: '1',
  name: 'Amani Tech',
  handle: '@amanitech',
  avatar: '👨‍💻',
  bio: '🚀 Full Stack Developer | Building the future | Open Source Contributor | Tech Enthusiast from Tanzania 🇹🇿',
  verified: true,
  premium: true,
  followers: 15420,
  following: 892,
  posts: 3241,
  joinedDate: 'March 2019',
  location: 'Dar es Salaam, Tanzania',
  website: 'amanitech.dev',
};

export const users: User[] = [
  currentUser,
  {
    id: '2',
    name: 'Zawadi Innovation',
    handle: '@zawadi_innov',
    avatar: '👩‍🔬',
    bio: 'Innovation Lead @TechAfrica | AI & ML Researcher | Speaker',
    verified: true,
    premium: true,
    followers: 89200,
    following: 432,
    posts: 12500,
    joinedDate: 'January 2018',
    location: 'Nairobi, Kenya',
  },
  {
    id: '3',
    name: 'Baraka Digital',
    handle: '@barakadigital',
    avatar: '🎨',
    bio: 'UI/UX Designer | Creative Director | Making pixels beautiful',
    verified: true,
    premium: false,
    followers: 45600,
    following: 1200,
    posts: 8900,
    joinedDate: 'June 2020',
  },
  {
    id: '4',
    name: 'Neema AI',
    handle: '@neema_ai',
    avatar: '🤖',
    bio: 'Artificial Intelligence Researcher | Deep Learning | NLP',
    verified: true,
    premium: true,
    followers: 125000,
    following: 234,
    posts: 5600,
    joinedDate: 'September 2017',
  },
  {
    id: '5',
    name: 'Furaha Dev',
    handle: '@furahadev',
    avatar: '👨‍🎓',
    bio: 'Software Engineer @BigTech | React | TypeScript | Node.js',
    verified: false,
    premium: false,
    followers: 8900,
    following: 567,
    posts: 2340,
    joinedDate: 'February 2021',
  },
  {
    id: '6',
    name: 'Upendo Crypto',
    handle: '@upendo_crypto',
    avatar: '💎',
    bio: 'Blockchain Developer | Web3 Enthusiast | DeFi Builder',
    verified: true,
    premium: true,
    followers: 67800,
    following: 345,
    posts: 9800,
    joinedDate: 'April 2019',
  },
  {
    id: '7',
    name: 'Rehema Cloud',
    handle: '@rehemacloud',
    avatar: '☁️',
    bio: 'Cloud Architect | AWS | GCP | DevOps | Infrastructure',
    verified: true,
    premium: false,
    followers: 34500,
    following: 678,
    posts: 6700,
    joinedDate: 'July 2018',
  },
];

export const posts: Post[] = [
  {
    id: '1',
    user: users[1],
    content: '🚀 Just launched our new AI-powered code review tool! It can detect bugs, suggest improvements, and even write documentation automatically.\n\nThe future of software development is here. What features would you like to see next?\n\n#AI #DevTools #Innovation',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    likes: 2341,
    retweets: 567,
    replies: 189,
    views: 89000,
    bookmarks: 432,
    liked: false,
    retweeted: false,
    bookmarked: false,
    isPremium: true,
  },
  {
    id: '2',
    user: users[2],
    content: '🎨 Design tip of the day:\n\nWhite space is not empty space — it\'s a powerful design element. Use it wisely to create hierarchy, improve readability, and make your designs breathe.\n\nLess is truly more in modern UI design.',
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    likes: 1892,
    retweets: 445,
    replies: 78,
    views: 56000,
    bookmarks: 890,
    liked: true,
    retweeted: false,
    bookmarked: false,
  },
  {
    id: '3',
    user: users[3],
    content: '🤖 Breaking: Our latest language model just passed the Turing test with 94% accuracy across 1000 evaluators.\n\nWe\'re entering a new era of human-AI interaction. The implications for education, healthcare, and creative industries are enormous.\n\nFull paper dropping next week.',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    likes: 15600,
    retweets: 4500,
    replies: 2300,
    views: 1200000,
    bookmarks: 8900,
    liked: false,
    retweeted: true,
    bookmarked: true,
    isPremium: true,
  },
  {
    id: '4',
    user: users[4],
    content: '💡 Hot take: TypeScript is not just "JavaScript with types." It\'s a completely different way of thinking about software architecture.\n\nOnce you go TS, you never go back. The confidence it gives you when refactoring is unmatched.\n\nWho agrees? 👇',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    likes: 3456,
    retweets: 789,
    replies: 567,
    views: 145000,
    bookmarks: 234,
    liked: false,
    retweeted: false,
    bookmarked: false,
  },
  {
    id: '5',
    user: users[5],
    content: '🔗 Web3 is not dead. It\'s just evolving.\n\nThe next wave of blockchain applications will focus on:\n\n• Real-world asset tokenization\n• Decentralized identity\n• Cross-chain interoperability\n• Zero-knowledge proofs for privacy\n\nWe\'re building the infrastructure for the next internet.',
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
    likes: 5678,
    retweets: 1234,
    replies: 456,
    views: 234000,
    bookmarks: 1567,
    liked: false,
    retweeted: false,
    bookmarked: false,
    isPremium: true,
  },
  {
    id: '6',
    user: users[6],
    content: '☁️ Cloud cost optimization checklist:\n\n✅ Right-size your instances\n✅ Use spot/preemptible instances\n✅ Implement auto-scaling\n✅ Clean up unused resources\n✅ Use reserved instances for predictable workloads\n✅ Monitor with cost alerts\n\nSaved our company $200K/year with these simple steps.',
    timestamp: new Date(Date.now() - 1000 * 60 * 120),
    likes: 8901,
    retweets: 2345,
    replies: 345,
    views: 567000,
    bookmarks: 4567,
    liked: true,
    retweeted: false,
    bookmarked: false,
  },
  {
    id: '7',
    user: users[0],
    content: '🌍 Excited to announce that our open-source project just hit 10,000 stars on GitHub!\n\nThank you to every contributor, bug reporter, and community member who made this possible.\n\nOpen source is the future. Let\'s keep building together! 🙏\n\n#OpenSource #GitHub #Community',
    timestamp: new Date(Date.now() - 1000 * 60 * 180),
    likes: 12345,
    retweets: 3456,
    replies: 789,
    views: 890000,
    bookmarks: 2345,
    liked: false,
    retweeted: false,
    bookmarked: false,
    isPremium: true,
  },
];

export const notifications: Notification[] = [
  {
    id: '1',
    type: 'like',
    user: users[1],
    content: 'liked your post',
    timestamp: new Date(Date.now() - 1000 * 60 * 2),
    read: false,
  },
  {
    id: '2',
    type: 'retweet',
    user: users[3],
    content: 'reposted your post',
    timestamp: new Date(Date.now() - 1000 * 60 * 10),
    read: false,
  },
  {
    id: '3',
    type: 'follow',
    user: users[4],
    content: 'followed you',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    read: false,
  },
  {
    id: '4',
    type: 'mention',
    user: users[2],
    content: 'mentioned you in a post',
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    read: true,
  },
  {
    id: '5',
    type: 'reply',
    user: users[5],
    content: 'replied to your post',
    timestamp: new Date(Date.now() - 1000 * 60 * 60),
    read: true,
  },
  {
    id: '6',
    type: 'like',
    user: users[6],
    content: 'liked your reply',
    timestamp: new Date(Date.now() - 1000 * 60 * 90),
    read: true,
  },
];

export const messages: Message[] = [
  {
    id: '1',
    user: users[1],
    lastMessage: 'Hey! Did you see the new AI features?',
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    unread: true,
  },
  {
    id: '2',
    user: users[2],
    lastMessage: 'The design mockups are ready for review 🎨',
    timestamp: new Date(Date.now() - 1000 * 60 * 30),
    unread: true,
  },
  {
    id: '3',
    user: users[3],
    lastMessage: 'Let\'s schedule a call about the research paper',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    unread: false,
  },
  {
    id: '4',
    user: users[5],
    lastMessage: 'Check out this smart contract pattern I found',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
    unread: false,
  },
];

export const trends: Trend[] = [
  { id: '1', category: 'Technology · Trending', name: '#AIRevolution', posts: '125K posts' },
  { id: '2', category: 'Trending in Tanzania', name: '#TechAfrica', posts: '89.2K posts' },
  { id: '3', category: 'Programming · Trending', name: 'TypeScript 6.0', posts: '67.8K posts' },
  { id: '4', category: 'Business · Trending', name: '#StartupLife', posts: '45.6K posts' },
  { id: '5', category: 'Science · Trending', name: 'Quantum Computing', posts: '34.5K posts' },
  { id: '6', category: 'Trending in East Africa', name: '#Innovation2026', posts: '28.9K posts' },
  { id: '7', category: 'Technology · Trending', name: '#WebDevelopment', posts: '23.4K posts' },
  { id: '8', category: 'Entertainment · Trending', name: '#OpenSource', posts: '19.8K posts' },
];
